name: BallSacBlocks
main: diamondgold\DummyItemsBlocks\Main
description: Registers (non-functional) items and blocks
version: 1.0.2
api: 5.6.0
load: STARTUP
author: diamond-gold (ace)
website: https://github.com/diamond-gold/DummyItemsBlocks
permissions:
    dummyitemsblocks.changestate:
        description: Allows changing of state by right-clicking
        default: op
